name:                lastfm-summary
version:             0.1.0.0
github:              "andrewcb/lastfm-summary"
license:             BSD3
author:              "Andrew Bulhak"
copyright:           "2018 Andrew Bulhak"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/andrewcb/lastfm-summary#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- text
- directory
- bytestring
- http-conduit
- aeson
- ConfigFile
- mtl
- MissingH
- optparse-applicative


library:
  source-dirs: src

executables:
  lastfm-summary:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lastfm-summary

tests:
  lastfm-summary-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lastfm-summary
    - hspec >= 1.8
    - string-quote
